# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E0v6BZPBwChWak3CVXKkw4d7RsHxDkd-
"""

import streamlit as st
import matplotlib.pyplot as plt
import numpy as np

# --- Core Engine: Ray Diagram Logic ---
def generate_gearbox_ray_diagram(stages, phi, n_input, g_type='closed', layout='bilateral'):
    n_stages = len(stages)

    # 1. Structural Characteristics (x) based on Type
    x = [1]
    if g_type == 'closed':
        for i in range(1, n_stages):
            x.append(int(np.prod(stages[:i])))
    elif g_type == 'open':
        for i in range(1, n_stages):
            x.append(int(np.prod(stages[:i]) + 1))
    elif g_type == 'cross':
        for i in range(1, n_stages):
            x.append(max(1, int(np.prod(stages[:i]) - 1)))

    # 2. Setup Figure
    fig, ax = plt.subplots(figsize=(12, 7))

    # Calculate Max Range for Y-axis scaling
    max_range_index = int(sum((p-1)*xi for p, xi in zip(stages, x)))
    y_nodes = np.arange(max_range_index + 1)

    # 3. Recursive Trace of Rays
    start_node = 0 if layout == 'unilateral' else max_range_index // 2
    current_nodes = [start_node]
    all_violations = []

    for s_idx, p in enumerate(stages):
        next_nodes = []
        xi = x[s_idx]

        for node in current_nodes:
            if layout == 'bilateral':
                steps = np.arange(p) - (p - 1) / 2
                jumps = [int(s * 2 * xi) if p % 2 == 0 else int(s * xi) for s in steps]
            else:
                jumps = [int(i * xi) for i in range(p)]

            for jump in jumps:
                target_node = node + jump
                next_nodes.append(target_node)

                # Feasibility Check: 0.25 <= i <= 2.0
                ratio = phi**jump
                is_feasible = 0.25 <= ratio <= 2.0
                if not is_feasible:
                    all_violations.append(ratio)

                color = '#2ecc71' if is_feasible else '#e74c3c'
                ax.plot([s_idx, s_idx+1], [node, target_node],
                        color=color, alpha=0.7, lw=2, linestyle='-' if is_feasible else '--')

        current_nodes = sorted(list(set(next_nodes)))

    # 4. Formatting
    ax.set_xticks(np.arange(n_stages + 1))
    ax.set_xticklabels([f"Shaft {i+1}" for i in range(n_stages + 1)])

    speed_labels = [f"{n_input * (phi**(i - start_node)):.1f}" for i in y_nodes]
    ax.set_yticks(y_nodes)
    ax.set_yticklabels(speed_labels)
    ax.set_ylabel("Speed (RPM)")
    ax.grid(True, linestyle=':', alpha=0.5)

    status = "FEASIBLE" if not all_violations else "NOT FEASIBLE"
    ax.set_title(f"Ray Diagram: {layout.upper()} - {g_type.upper()} ({status})",
                 fontsize=14, fontweight='bold', color='#27ae60' if not all_violations else '#c0392b')

    return fig, not all_violations

# --- Streamlit UI: The Web Interface ---
st.set_page_config(page_title="IPE Gearbox Designer", page_icon="⚙️")

st.title("⚙️ Machine Tool Gearbox Designer")
st.markdown("Use this tool to generate ray diagrams and check the feasibility of structural formulas for machine tool speed boxes.")

with st.sidebar:
    st.header("Design Parameters")
    stages_str = st.text_input("Stages (comma separated)", "3, 2")
    phi = st.selectbox("Geometric Progression (φ)", [1.06, 1.12, 1.26, 1.41, 1.58], index=2)
    n_input = st.number_input("Input RPM", value=160)

    st.divider()
    g_type = st.radio("Structural Type", ["closed", "open", "cross"], help="Closed: No overlap. Cross: Overlapping speeds.")
    layout = st.radio("Visual Layout", ["bilateral", "unilateral"], help="Bilateral is the standard compact design.")

if st.button("Generate & Validate Diagram", type="primary"):
    try:
        # Convert input string to list
        stages = [int(x.strip()) for x in stages_str.split(",")]

        # Generate the diagram
        fig, is_feasible = generate_gearbox_ray_diagram(stages, phi, n_input, g_type, layout)

        # Display the plot
        st.pyplot(fig)

        # Display feedback
        if is_feasible:
            st.success("✅ **Design Feasible!** All transmission ratios are within the 0.25 to 2.0 range.")
        else:
            st.error("❌ **Design Not Feasible!** Red dashed lines indicate ratios outside the 0.25 - 2.0 boundary.")
            st.warning("Try reducing the value of φ or rearranging the structural stages.")

    except Exception as e:
        st.error(f"Please check your input format. Error: {e}")

st.divider()
st.caption("Developed for IPE Machine Tools Study | Exam Prep April 2026")
